### ISSUE TITLE
Is this repo still valid?

### ISSUE THREAD

**Issue by akauppi** [zalando/docker-openjdk#14]
At least `cdp-controller-deploy` [refers to this repo](https://github.bus.zalan.do/continuous-delivery/cdp-controller-deploy/blob/5dbb5dc59216cabad7b4598eb024a7373eac33fb/deploy/apply/kube-deployment.yaml#L119) (Zalando internal link).

@hjacobs Is the repo still valid? It looks very stale, based on the most recent changes, and releases.
The latest OpenJDK release I know of is `registry.opensource.zalan.do/stups/openjdk:1.8.0-131-7`.

If this repo is no longer being maintained, I think the README should say so, and point to where the action has moved.

**Comment by hjacobs** [comment]
Yes, this repo is still valid and we are building with CDP (https://github.com/zalando-stups/docker-openjdk/blob/master/delivery.yaml). 

I just realize that we can now introduce a CDP dependency to our base Ubuntu image, so I will create a PR.. :smile:
